panels:
  type: Hexagon#0
  rows: 10
  columns: 19
  side_length: 5.0e-2
  spacing: 5.0e-3
  initial_tiling: [[3, 7], [3, 11], [4, 8], [4, 10], [4, 7], [4, 9], [4, 11], [5, 6], [5, 8], [5, 10], [5, 12], [5, 7], [5, 9], [5, 11], [6, 8], [6, 10], [6, 7], [6, 11]]

routing:
  tiles_per_segment: 5

materials:
  leds:
    BTF Amazon (1m, 60lpm):
      number_of_leds: 60
      leds_per_meter: 60
      watts: 18.0
      cost: 16.99
      url: https://www.amazon.fr/dp/B01CDTED80/ref=redir_mobile_desktop?_encoding=UTF8&aaxitk=729c820e4b1be5ecb44cff4d0da53f66&content-id=amzn1.sym.962b535b-a8b7-499f-8ba5-164fe04b0459%3Aamzn1.sym.962b535b-a8b7-499f-8ba5-164fe04b0459&hsa_cr_id=8318593460202&pd_rd_plhdr=t&pd_rd_r=a79297a1-ed98-4868-bf1a-b2e6d7878817&pd_rd_w=sKxPG&pd_rd_wg=zrPeh&qid=1663607962&ref_=sbx_be_s_sparkle_mcd_asin_0_img&sr=1-1-fd947bf3-57d2-4cc9-939d-2805f92cef28&th=1

    BTF Amazon (5m, 60lpm):
      number_of_leds: 300
      leds_per_meter: 60
      watts: 45.0
      cost: 46.99
      url: https://www.amazon.fr/dp/B01CDTEJBG/ref=redir_mobile_desktop?_encoding=UTF8&aaxitk=729c820e4b1be5ecb44cff4d0da53f66&content-id=amzn1.sym.962b535b-a8b7-499f-8ba5-164fe04b0459%3Aamzn1.sym.962b535b-a8b7-499f-8ba5-164fe04b0459&hsa_cr_id=8318593460202&pd_rd_plhdr=t&pd_rd_r=a79297a1-ed98-4868-bf1a-b2e6d7878817&pd_rd_w=sKxPG&pd_rd_wg=zrPeh&qid=1663607962&ref_=sbx_be_s_sparkle_mcd_asin_0_img&sr=1-1-fd947bf3-57d2-4cc9-939d-2805f92cef28&th=1

    BTF Amazon (5m, 30lpm):
      number_of_leds: 150
      leds_per_meter: 30
      watts: 45.0
      cost: 30.99
      url: https://www.amazon.fr/dp/B01CDTECSG/ref=redir_mobile_desktop?_encoding=UTF8&aaxitk=729c820e4b1be5ecb44cff4d0da53f66&content-id=amzn1.sym.962b535b-a8b7-499f-8ba5-164fe04b0459%3Aamzn1.sym.962b535b-a8b7-499f-8ba5-164fe04b0459&hsa_cr_id=8318593460202&pd_rd_plhdr=t&pd_rd_r=a79297a1-ed98-4868-bf1a-b2e6d7878817&pd_rd_w=sKxPG&pd_rd_wg=zrPeh&qid=1663607962&ref_=sbx_be_s_sparkle_mcd_asin_0_img&sr=1-1-fd947bf3-57d2-4cc9-939d-2805f92cef28&th=1

  sheets:
    acrylic 30x40 leroy-merlin:
      size: [30.0e-2, 40.0e-2]
      cost: 4.60

    acrylic 40x50 leroy-merlin:
      size: [40.0e-2, 50.0e-2]
      cost: 7.20

    acrylic 50x70 leroy-merlin:
      size: [50.0e-2, 70.0e-2]
      cost: 10.90

    acrylic 60x90 leroy-merlin:
      size: [60.0e-2, 90.0e-2]
      cost: 14.90

    shower film leroy-merlin:
      size: [250.0e-2, 90.0e-2]
      cost: 29.90

assembly:
  leds:
    - ["BTF Amazon (1m, 60lpm)", "BTF Amazon (5m, 60lpm)"]
    - ["BTF Amazon (5m, 30lpm)"]
  sheets:
    - ["shower film leroy-merlin"]
    - ["acrylic 30x40 leroy-merlin", "acrylic 40x50 leroy-merlin", "acrylic 50x70 leroy-merlin", "acrylic 60x90 leroy-merlin"]
