panels:
  type: Hexagon#0
  rows: 10
  columns: 19
  side_length: 5.0e-2
  spacing: 5.0e-3
  initial_tiling: [[3, 7], [3, 11], [4, 8], [4, 10], [4, 7], [4, 9], [4, 11], [5, 6], [5, 8], [5, 10], [5, 12], [5, 7], [5, 9], [5, 11], [6, 8], [6, 10], [6, 7], [6, 11]]

routing:
  tiles_per_segment: 5
